name: Run tests

on:
  push:
    branches: [ main ]
    tags: 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.6
    - name: Install OpenModelica
      uses: THM-MoTE/setup-openmodelica@v1
      with:
        version: 1.17.0
    - name: Install Modelica standard library
      run: sudo apt-get install omlib-modelica-3.2.3
    - name: Install Julia requirements
      run: |
        export PYTHON=""
        julia --project=. -e 'using Pkg; Pkg.instantiate()'
    - name: Run unit tests
      run: julia --project=. scripts/unittests.jl
